apiVersion: v1
kind: Pod
metadata:
  name: sns-modify-enricher
spec:
  containers:
  - image: sns-modify-enricher:0.1.1
    name: sns-modify-enricher
    imagePullPolicy: Never
    env:
      - name: KAFKA_BROKER_SERVER
        valueFrom:
          configMapKeyRef:
            name: kafka-broker-config
            key: KAFKA_BROKER_SERVER
      - name: KAFKA_BROKER_PORT
        valueFrom:
          configMapKeyRef:
            name: kafka-broker-config
            key: KAFKA_BROKER_PORT